// <auto-generated />
using System;
using Argus.Operations.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Argus.Operations.Infrastructure.Migrations
{
    [DbContext(typeof(ArgusDbContext))]
    partial class ArgusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Brigada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_BRIGADA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVA");

                    b.Property<string>("BaseOperacional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("BASE_OPERACIONAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("BRIGADA", (string)null);
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Brigadista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_BRIGADISTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<long>("BrigadaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_BRIGADA");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ADMISSAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("FUNCAO");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("MATRICULA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("BrigadaId");

                    b.ToTable("BRIGADISTA", (string)null);
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlertaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<long>("BrigadaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_BRIGADA");

                    b.Property<long>("BrigadistaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_BRIGADISTA");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ABERTURA");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_FINALIZACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("BrigadaId");

                    b.HasIndex("BrigadistaId");

                    b.ToTable("OCORRENCIA", (string)null);
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Recurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_RECURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BrigadaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_BRIGADA");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("DISPONIVEL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("BrigadaId");

                    b.ToTable("RECURSO", (string)null);
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.RegistroCampo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGISTRO_CAMPO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<long>("OcorrenciaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_OCORRENCIA");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("URL_FOTO");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.ToTable("REGISTRO_CAMPO", (string)null);
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<int>("Perfil")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERFIL");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_LOGIN");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Brigadista", b =>
                {
                    b.HasOne("Argus.Operations.Domain.Entities.Brigada", "Brigada")
                        .WithMany()
                        .HasForeignKey("BrigadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brigada");
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Argus.Operations.Domain.Entities.Brigada", "Brigada")
                        .WithMany()
                        .HasForeignKey("BrigadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Argus.Operations.Domain.Entities.Brigadista", "Brigadista")
                        .WithMany()
                        .HasForeignKey("BrigadistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brigada");

                    b.Navigation("Brigadista");
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.Recurso", b =>
                {
                    b.HasOne("Argus.Operations.Domain.Entities.Brigada", "Brigada")
                        .WithMany()
                        .HasForeignKey("BrigadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brigada");
                });

            modelBuilder.Entity("Argus.Operations.Domain.Entities.RegistroCampo", b =>
                {
                    b.HasOne("Argus.Operations.Domain.Entities.Ocorrencia", "Ocorrencia")
                        .WithMany()
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ocorrencia");
                });
#pragma warning restore 612, 618
        }
    }
}
